### ISSUE TITLE
ZulfBungee bug

### ISSUE THREAD

**Issue by Deichor** [Zulfen/ZulfBungee#15]
**Describe the bug**
Proxy connections are lost when I join the server.

**To reproduce**
-

**Expected behavior**
I expected the connections not to break.

**Screenshots**
![image](https://user-images.githubusercontent.com/43517719/221398538-bdbba108-ffa9-4c74-9153-21fa585c1e62.png)

**Spigot server information (in this order)**
 - Plugin version: 0.8.5
 - Minecraft Version: 1.19.3
 - Skript Version: 2.6.4
 - Java Version: 19

**Proxy information (in this order)**
 - Proxy Type: Waterfall
 - Plugin Version: 0.8.5
 - Minecraft Version: 1.19.3
 - Java Version: 19

**Additional context**
Default

**Comment by Zulfen** [comment]
Should be fixed now :)
