### ISSUE TITLE
[BUG] Connection restart spigot isn't correct

### ISSUE THREAD

**Issue by Lennord** [Zulfen/ZulfBungee#17]
**Describe the bug**
When I turn on my bungeecord server then after the spigot server, when I turn off the spigot server and turn it on again it does not connect me directly to the bungeecord (I have to restart the bungeecord for it to reconnect), which is disturbing.

There is no error with the debug-mode of the 2 servers (bungeecord and spigot).

I just noticed that if we leave the 2 servers after the bug, the server reconnects but long after (about 5 to 10 minutes).

The problem is only related to localhost because on a vps and a panel it works very well.

**Spigot server information (in this order)**
 - Plugin version: 0.9.0-ALPHA
 - Minecraft Version: 1.18.2 (Paper-388)
 - Skript Version: 2.6.4
 - Java Version: 17.0.4

**Proxy information (in this order)**
 - Proxy Type: Waterfall Latest
 - Plugin Version: 0.9.0-ALPHA
 - Minecraft Version: 1.19
 - Java Version: 17.0.4

**Comment by Zulfen** [comment]
Will investigate this!

**Comment by Zulfen** [comment]
Hoping latest update fixed this :)

**Comment by Lennord** [comment]
> Hoping latest update fixed this :)

Hello, it still doesn't work, it tells me "[Zulu Bungee] Attempting to connect..." when I restart my Spigot server suddenly I have to turn off the bungeecord and the spigot at the same time to restart the bungeecord first then the Spigot server.

**Comment by Zulfen** [comment]
This should hopefully be improved with 0.9.3

**Comment by Lennord** [comment]
> This should hopefully be improved with 0.9.3

Good evening, I tested your version 0.9.3 and it gives me this error when reconnecting to the bungeecord (with debug-mode) on the Spigot console fails.

When I restart the Spigot leaving the Bungeecord on, it does not reconnect directly and sometimes it reconnects correctly but it is quite rare according to my tests.

`[22:16:36 WARN]: [ZulfBungee] Could not connect to the proxy!:`
`[22:16:36 WARN]: [ZulfBungee] java.base/sun.nio.ch.Net.connect0(Native Method)`
`[22:16:36 WARN]: [ZulfBungee] java.base/sun.nio.ch.Net.connect(Net.java:579)`
`[22:16:36 WARN]: [ZulfBungee] java.base/sun.nio.ch.Net.connect(Net.java:568)`

**Comment by Lennord** [comment]
I saw that you delete and put 0.9.3 and I stayed and it's the same as what I said above.

**Comment by Lennord** [comment]
I tested the last released version (0.9.4) and it still doesn't work unfortunately.

**Comment by Lennord** [comment]
Good evening, following your update (0.9.5) and with the 2 new configurations, it works perfectly.

Thank you very much for these solved problems.

**Comment by Zulfen** [comment]
Awesome! Thanks for letting me know!
