### ISSUE TITLE
Better Global Scripts

### ISSUE THREAD

**Issue by ANDREI12333** [Zulfen/ZulfBungee#2]
# **Better Global Scripts**
Global Scripts would work a lot better if they had things like being able to reload only a specific script at a time, The following subcommands to the `scripts` part of the `/zulfbungee` command would work nicely if they were added:
- disable {scriptname[.sk]}
- enable {scriptname[.sk]}

**Comment by Zulfen** [comment]
You mean scripts that sync across the network? Global scripts do that already :) there is a scripts folder in the plugin folder which you can reload by doing `/zulfbungee scripts reload`.
If you meant something else, let me know.

**Comment by ANDREI12333** [comment]
@Zulfen would work a little better if there was some qof (Quality of Life) features like `/zulfbungee scripts disable {skriptname}[.sk]` and `/zulfbungee scripts enable {scriptname[.sk]}` and a optional argument of `{skriptname}[.sk]` to the `/zulfbungee scripts reload` command.

**Comment by Zulfen** [comment]
Ohh okay, see what you mean now! Thanks for the suggestion!

**Comment by ANDREI12333** [comment]
@Zulfen I've upaded my issue to represent more what I actually meant.
