### ISSUE TITLE
Case sensitive network variables

### ISSUE THREAD

**Issue by trushniuser** [Zulfen/ZulfBungee#29]
**Describe the bug**
Network variables are case sensitive. For example {a} isn't equal to {A}, which means it is hard to make player nicknames in network variables when you can't write the exact nickname of player, so player with nickname "bob" isn't equal to "BoB"

**To reproduce**
command /skripttest:
	trigger:
		set {_a} to "1"
		set {_A} to "0"
		send "%{_a}% %{_A}%"
		set network variable {a} to "1"
		set network variable {A} to "0"
		send "%network variable {a}% %network variable {A}%"

**Expected behavior**
I expected that network variables {a} and {A} would be 0, but not different. Also I use /find command made in ZulfBungee. I use network variable {name::%arg%} to get special nickname of player, so {name::adminplayer} becomes &##121212ADMIN Player. But with case sensitive it makes some problems because {name::adminplayer} and {name::ADMINplayer} aren't equal to each other.

**Screenshots**
https://imgur.com/qPCLiVK

**Spigot server information (in this order)**
 - Plugin version 0.9.8
 - Minecraft Version: 1.18.2
 - Skript Version 2.6.4
 - Java Version 17

**Proxy information (in this order)**
 - Proxy Type Bungeecord
 - Plugin Version 0.9.8
 - Minecraft Version: 1.18.2
 - Java Version 11

**Comment by Lennord** [comment]
I also have this problem, I hope it will be fixed as soon as possible.

**Comment by Zulfen** [comment]
Hi! Thanks for reporting this, currently looking into it. Currently starting exam season right now so a fix might have to wait till the end of the week.

**Comment by Zulfen** [comment]
Hello again, this should be fixed in the [latest pre-release build.](https://github.com/Zulfen/ZulfBungee/releases/tag/v0.9.8-pre2)
You will need to add the option `case-insensitive-variables: true` to the plugin's config on the proxy side for it to work.
If it still doesn't behave as expected, please let me know!

**Comment by trushniuser** [comment]
There's also problem with expressions like %arg's current server%, so player's current server != PLAYER's current server
