### ISSUE TITLE
Proxy Error when joining the server

### ISSUE THREAD

**Issue by Abendsaufstehen** [Zulfen/ZulfBungee#33]
**Whats the issue and how to reproduce**
When joining the server you get a error message in proxy and the plugin restablishs connection with one of my servers all the time (Error comming at next to screenshot)

**Expected behavior**
No error in the console

**Screenshots**
![image](https://github.com/Zulfen/ZulfBungee/assets/120741880/d69dcdc0-05ec-403f-ba5c-bad41343fae3)
`[21:33:29 ERROR] [zulfbungee]: Unhandled exception occurred in connection with address /127.0.0.1:2002
[21:33:29 ERROR]: java.lang.NullPointerException: Cannot invoke "tk.zulfengaming.zulfbungee.universal.socket.objects.client.ClientPlayer.getUuid()" because "clientPlayerIn" is null
[21:33:29 ERROR]:       at tk.zulfengaming.zulfbungee.velocity.ZulfVelocity.getPlayer(ZulfVelocity.java:157)
[21:33:29 ERROR]:       at tk.zulfengaming.zulfbungee.universal.socket.packets.ProxyPlayerPermission.handlePacket(ProxyPlayerPermission.java:27)
[21:33:29 ERROR]:       at tk.zulfengaming.zulfbungee.universal.managers.PacketHandlerManager.handlePacket(PacketHandlerManager.java:50)
[21:33:29 ERROR]:       at tk.zulfengaming.zulfbungee.universal.socket.BaseServerConnection.processPacket(BaseServerConnection.java:116)
[21:33:29 ERROR]:       at tk.zulfengaming.zulfbungee.universal.socket.BaseServerConnection.run(BaseServerConnection.java:95)
[21:33:29 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:275)
[21:33:29 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:33:29 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
` and here the issue

**Spigot server information (in this order)**
 - ZulfBungee 0.9.7
 - Paper Servers - 1.20.1
 - Skript Version: 2.7.0-beta3 (skriptlang-github)
 - java version "20.0.1" 2023-04-18; Java(TM) SE Runtime Environment (build 20.0.1+9-29); Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

**Proxy information (in this order)**
 - Veloctiy 3.2.0
 - ZulfBungee 0.9.7
 - Paper Server - 1.20.1
 - java version "20.0.1" 2023-04-18; Java(TM) SE Runtime Environment (build 20.0.1+9-29); Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

**Additional context**
**THE CONFIG OF THE SERVER WHO CAUSES THE ISSUE**:
# - Key Setup -

# The port which you defined in your proxy config.
server-port: 8000

# The IP of your proxy.
server-host: "127.0.0.1"

# The port which this client (this Spigot server) will bind to, so it can listen for the proxy.
client-port: 2002
# If you don't mind what port it chooses to bind to (e.g. your proxy and client are both on the same machine)
# you can set this to true.
choose-random-port: false

# The IP this client will bind to.
# This should usually be left as 0.0.0.0, or 127.0.0.1, but feel free to change this if you need to -
# (i.e. you are on shared hosting / Pterodactyl)
client-host: "0.0.0.0"

# If your proxy cannot find the name of your server from its config, or if you want to define a custom one -
# specify it here. This is usually always done automatically and can be left blank.
# Ideally, make sure it matches the name that's defined in your proxy server software's config.
forced-connection-name: ""

# This will toggle the display of detailed messages about what is going to the console.
# When filing a bug report / checking for issues, this is extremely useful to know what exactly went wrong!
debug: false

**VELOCTIY CONFIG**
# - Key Setup -

# This is the port that this server will bind to, which will it listen for incoming connections on.
port: 8000

# The IP that this server will bind to. Similar to the "client-host" in the Spigot config.
# This should usually be left as 0.0.0.0, or 127.0.0.1, but feel free to change this if you need to -
# (i.e. you are on shared hosting / Pterodactyl)
host: "0.0.0.0"

# - Options -

# This will toggle the display of detailed messages about what is going to the console.
# When filing a bug report / checking for issues, this is extremely useful to know what exactly went wrong!
debug: false

# Enables or disables global scripts.
global-scripts: true

# - Storage -

# What kind of database should be used to store network variables.
# Currently, supported databases: MySQL, H2

# If you have no clue what this does, just leave this as the default.
storage-type: "h2"

# Each option should be self-explanatory if you know what you are doing.

# If you are using H2, this will not apply - these two settings only apply to remote databases.
storage-host: "localhost"
storage-port: 3306

# !! Change these from the default to improve security !!
storage-username: "username"
storage-password: "password"

storage-database: "database"

# [MySQL Setup]

# If you get errors in console because of SSL, disable it here, but it's better to set up SSL on the MySQL server.
mysql-use-ssl: true
mysql-verify-certificate: true

**Comment by Zulfen** [comment]
Should be fixed in the latest release.
