### ISSUE TITLE
Issue for connecting the addon on Pterodactyl panel

### ISSUE THREAD

**Issue by MaitreFranck** [Zulfen/ZulfBungee#9]
**Describe the bug**
Hello, i tried many configuration with pterodactyl to make this addon work, i've ports opened on both proxy and spigot but it didn't want to connect. I tried all IP, 127.0.0.1, 0.0.0.0, 172.18.0.1 and the IP of my VPS.

Has you advises on how you can connect ?

I'm on bungeecord/waterfall and paper, tried with latest (0.8.0)

I can send you screenshots of differents configurations if you need.

**Comment by Zulfen** [comment]
Could you turn on debug mode on the Spigot, send me the output and also your plugin config for both the Bungeecord and Spigot?

I have had issues with Pterodactyl in the past, so hopefully I can find out what causes this!

**Comment by Zulfen** [comment]
Just wanna check - guessing you are running Pterodactyl yourself and know how to configure it?
What addresses have you configured for the Spigot servers in the Bungeecord config?

**Comment by MaitreFranck** [comment]
Yes i installed it myself on my vps, i have full access on it.

Spigot : 

[ClientListenerManager/INFO]: [ZulfBungee] Thread has arrived: ClientListenerManager
[DataIn/INFO]: [ZulfBungee] Thread has arrived: DataIn
[ClientConnection/INFO]: [ZulfBungee] Thread has arrived: ClientConnection
[DataOut/INFO]: [ZulfBungee] Thread has arrived: DataOut
[ClientListenerManager/WARN]: [ZulfBungee] Connection lost with proxy, attempting to connect every 2 seconds...
[ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Invalid argument (connect failed)
[ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Invalid argument (connect failed)
[ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Invalid argument (connect failed)
[ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Invalid argument (connect failed)

Also got this on another try : 

[21:17:50] [ClientConnection/INFO]: [ZulfBungee] Thread has arrived: ClientConnection
[21:17:50] [DataIn/INFO]: [ZulfBungee] Thread has arrived: DataIn
[21:17:50] [DataOut/INFO]: [ZulfBungee] Thread has arrived: DataOut
[21:17:50] [ClientListenerManager/WARN]: [ZulfBungee] Connection lost with proxy, attempting to connect every 2 seconds...
[21:17:52] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[21:17:54] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[21:17:56] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[21:17:58] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[21:18:00] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[21:18:02] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[21:18:04] [ClientListenerManager/INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)

Currently i don't have any firewall turned on iirc.

[bungee_config.txt](https://github.com/Zulfen/ZulfBungee/files/10684710/bungee_config.txt)

[spigot_config.txt](https://github.com/Zulfen/ZulfBungee/files/10684716/spigot_config.txt)

**Comment by Zulfen** [comment]
Do you mind showing me your Pterodactyl allocations?
https://pterodactyl.io/community/games/minecraft.html

I think that might have something to do with it. What

**Comment by Zulfen** [comment]
Depending what distro you use, also make sure your firewall is configured using the guide I linked just in case a firewall is automatically in place :)

**Comment by Zulfen** [comment]
If you use ufw, try this:
`ufw allow in on pterodactyl0 to 172.18.0.1 port 25500 proto tcp`
`ufw allow in on pterodactyl0 to 172.18.0.1 port 25570 proto tcp`

**Comment by Zulfen** [comment]
If you need further help with this, I could do a Discord call to help you configure if it still doesnt work.

**Comment by MaitreFranck** [comment]
I dont have ufw on my vps, but iptables with this settings : https://pastebin.com/pesQ5x1p

Concerning this : https://pterodactyl.io/community/games/minecraft.html it's what i followed, so my allocations looks like that : 
![image](https://user-images.githubusercontent.com/44005247/217640901-9d88bf0a-4d65-4184-a7f6-5f3eb5133a42.png)

And on the spigot : 
![image](https://user-images.githubusercontent.com/44005247/217641087-91f8888d-d16e-4ea9-b318-c1360a1d1fc7.png)

**Comment by MaitreFranck** [comment]
On bungee config.yml, i have my spigot setuped this way : 
![image](https://user-images.githubusercontent.com/44005247/217641845-5d8696d6-8f48-450d-9776-d6fbc549cfb8.png)

**Comment by Zulfen** [comment]
On your spigot server's server.properties, what do you have as the address in there? Just wanna get an idea of what goes where basically.

**Comment by MaitreFranck** [comment]
On spigot server's server.properties, it is set to 0.0.0.0, and server port is the primary in allocations tab so 25566.

**Comment by Zulfen** [comment]
Can you try these configs?
[bungee_config.txt](https://github.com/Zulfen/ZulfBungee/files/10695188/bungee_config.txt)
[spigot_config.txt](https://github.com/Zulfen/ZulfBungee/files/10695189/spigot_config.txt)

**Comment by MaitreFranck** [comment]
These ones print me this on the spigot : 

[16:33:42 INFO]: [ZulfBungee] Thread has arrived: ClientListenerManager
[16:33:42 INFO]: [Skript] Loading variables...
[16:33:42 INFO]: [Skript] Loaded 81 variables in 0.0 seconds
[16:33:42 INFO]: [Skript] All scripts loaded without errors.
[16:33:42 WARN]: [Skript] No scripts were found, maybe you should write some ;) (config.sk, line 188: databases:')
[16:33:42 INFO]: [Skript] Finished loading.
[16:33:42 INFO]: [ZulfBungee] Thread has arrived: ClientConnection
[16:33:42 INFO]: [ZulfBungee] Thread has arrived: DataIn
[16:33:42 INFO]: [ZulfBungee] Thread has arrived: DataOut
[16:33:42 WARN]: [ZulfBungee] Connection lost with proxy, attempting to connect every 2 seconds...
[16:33:44 INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[16:33:46 INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)
[16:33:48 INFO]: [ZulfBungee] Error while creating socket: java.net.ConnectException: Connection refused (Connection refused)

**Comment by Zulfen** [comment]
That's really odd... my only suggestion at this point is to try different combinations.
0.0.0.0 always used to work with Pterodactyl for me, but I believe those ports were open to the Internet, so not sure.

**Comment by MaitreFranck** [comment]
Okay so with your config file, I tried to replace server-host with 172.18.0.1, and it lead me to that :

Spigot side : 
![image](https://user-images.githubusercontent.com/44005247/217881582-bc41ba92-3d27-499d-ac67-8c56f1057571.png)

Bungeecord side : 
![image](https://user-images.githubusercontent.com/44005247/217881709-6d047018-edd3-4ae4-a971-75783929355e.png)

**Comment by Zulfen** [comment]
Awesome! This means that it appears that at least they can talk to eachother.
![image](https://user-images.githubusercontent.com/38318382/217892031-627b4ce0-0b3a-4abd-802d-6b9ce6913300.png)
Is your Bungeecord server still defined like this with the same address? If it is, just disable port whitelisting and the plugin should work!

**Comment by MaitreFranck** [comment]
On bungeecord's config.yml, it's like this : 
![image](https://user-images.githubusercontent.com/44005247/217893039-0a7a5c50-1aa0-4bef-b6a1-112a45380e5a.png)

**Comment by MaitreFranck** [comment]
But the port whitelisting is already disabled : 
![image](https://user-images.githubusercontent.com/44005247/217893289-110c8e11-a13b-4530-b748-19e6cb34773e.png)

**Comment by Zulfen** [comment]
> On bungeecord's config.yml, it's like this : ![image](https://user-images.githubusercontent.com/44005247/217893039-0a7a5c50-1aa0-4bef-b6a1-112a45380e5a.png)

Try replacing 0.0.0.0 with 172.18.0.1

**Comment by MaitreFranck** [comment]
Well I can't replace this line, every time i start the bungee, it's automaticly replaced with 0.0.0.0 (probably due to the way that ptero/docker works).

**Comment by Zulfen** [comment]
Oh okay. I'm gonna release an update soon which hopefully allows Pterodactyl to work, thanks for providing info :)

**Comment by MaitreFranck** [comment]
Okay, I'm gonna wait it with impatience, I hope it will work. If not, I will probably have to think about removing pterodactyl panel I guess

**Comment by Zulfen** [comment]
Hi! Have just released an experimental build which might fix the issue.
https://github.com/Zulfen/ZulfBungee/releases/download/v0.8.2-TEST/ZulfBungee.jar
Tell me if it works!

**Comment by MaitreFranck** [comment]
Seems good, but the port whitelist doesn't works if turned on. On proxy i got this : 

https://pastebin.com/4hVYt4uk

**Comment by MaitreFranck** [comment]
And the test.sk skript seems to not really work : 
![image](https://user-images.githubusercontent.com/44005247/218168536-5cfc0df2-08f9-4360-9299-6c882390a4a6.png)

**Comment by Zulfen** [comment]
What does the Spigot's console look like with debug mode on?

**Comment by Zulfen** [comment]
I'm just gonna remove the security system I think - it's been causing loads of problems and I only understand now that it's not needed. Will release a new update very soon to hopefully fix it

**Comment by Zulfen** [comment]
I'm hoping this works - done a couple of fixes:
https://github.com/Zulfen/ZulfBungee/releases/download/v0.8.2-TEST/ZulfBungee.jar

**Comment by MaitreFranck** [comment]
Everything seems good, thanks alot !
I only noticed one thing : 
![image](https://user-images.githubusercontent.com/44005247/218208377-54450aee-e2b3-473d-87e8-5abd1bf6e2fb.png)
Idk if this line doesn't works or not, but I tried to add that but doesn't change alot of thing : 
![image](https://user-images.githubusercontent.com/44005247/218208869-cf9a69a9-2817-408f-9e8a-94fc0062749a.png)

**Comment by MaitreFranck** [comment]
One more thing, has you tested your addon on a network with dozens of peoples ? Or is there a limit where it can start to be a little lagguy ?

**Comment by MaitreFranck** [comment]
I also maybe have a little improvement for global scripts, its a really good feature, but it can be nice to send them into a folder in Skript/scripts like we can have our scripts on each server on Skript/scripts/ZulfBungee/* and our skripts we only want in a specific server on Skript/scripts/*

Idk if you wanted me to add this on a new issue or not, so let me know :)

**Comment by MaitreFranck** [comment]
And one little little more thing, it seems that it sometimes "connect" 2 times the server, so that means it reload 2 times all the scripts : 
![image](https://user-images.githubusercontent.com/44005247/218212848-88b8b85c-291b-4be9-848d-f9068215e0de.png)
It could lead to 2x more time to reload all the global scripts (this is a bug i guess).

**Comment by Zulfen** [comment]
Thanks for the suggestion, glad to hear everything is working! :D

> Everything seems good, thanks alot ! I only noticed one thing : ![image](https://user-images.githubusercontent.com/44005247/218208377-54450aee-e2b3-473d-87e8-5abd1bf6e2fb.png) Idk if this line doesn't works or not, but I tried to add that but doesn't change alot of thing : ![image](https://user-images.githubusercontent.com/44005247/218208869-cf9a69a9-2817-408f-9e8a-94fc0062749a.png)

It should be event-text instead of event-string. My bad - think I put the wrong thing on SkriptHub!



> One more thing, has you tested your addon on a network with dozens of peoples ? Or is there a limit where it can start to be a little lagguy ?

Not really sure performance wise - I know network variables can get a little slow, but planning on adding some new syntax to get around a limitation. 

> I also maybe have a little improvement for global scripts, its a really good feature, but it can be nice to send them into a folder in Skript/scripts like we can have our scripts on each server on Skript/scripts/ZulfBungee/* and our skripts we only want in a specific server on Skript/scripts/*
> 
> Idk if you wanted me to add this on a new issue or not, so let me know :)

Good suggestion, will definitely consider this!
